BEGIN;

INSERT INTO artist (name, country, genre, created_at, updated_at)
VALUES

('Legião Urbana', 'Brasil', 'Rock', now(), now()),
('Titãs', 'Brasil', 'Rock', now(), now()),
('Skank', 'Brasil', 'Pop Rock', now(), now()),
('Capital Inicial', 'Brasil', 'Rock', now(), now()),
('Os Paralamas do Sucesso', 'Brasil', 'Rock/Reggae', now(), now()),
('Jota Quest', 'Brasil', 'Pop Rock', now(), now()),
('Charlie Brown Jr.', 'Brasil', 'Rock/Hardcore', now(), now()),
('Barão Vermelho', 'Brasil', 'Rock', now(), now()),
('Cássia Eller', 'Brasil', 'MPB/Rock', now(), now()),
('Marisa Monte', 'Brasil', 'MPB', now(), now()),
('Gilberto Gil', 'Brasil', 'MPB', now(), now()),
('Caetano Veloso', 'Brasil', 'MPB', now(), now()),
('Lulu Santos', 'Brasil', 'Pop Rock', now(), now()),
('Fresno', 'Brasil', 'Emo Rock', now(), now()),
('NX Zero', 'Brasil', 'Pop Rock', now(), now()),
('Metallica', 'USA', 'Heavy Metal', now(), now()),
('Nirvana', 'USA', 'Grunge', now(), now()),
('Pearl Jam', 'USA', 'Rock', now(), now()),
('Stereophonics, 'UK', 'Rock', now(), now()),
('Serj Tankian, 'USA', 'Rock', now(), now()),
('Guns N’ Roses , 'USA', 'Rock', now(), now()),
('Mike Shinoda  , 'USA', 'Rock', now(), now()),
('Red Hot Chili Peppers', 'USA', 'Funk Rock', now(), now()),
('Linkin Park', 'USA', 'Alternative Rock', now(), now()),
('Coldplay', 'UK', 'Alternative Rock', now(), now()),
('U2', 'Ireland', 'Rock', now(), now()),
('Queen', 'UK', 'Rock', now(), now()),
('The Beatles', 'UK', 'Rock', now(), now()),
('Pink Floyd', 'UK', 'Progressive Rock', now(), now()),
('AC/DC', 'Australia', 'Hard Rock', now(), now()),
('Imagine Dragons', 'USA', 'Pop Rock', now(), now()),
('Arctic Monkeys', 'UK', 'Indie Rock', now(), now()),
('Bon Jovi', 'USA', 'Hard Rock', now(), now()),
('Evanescence', 'USA', 'Alternative Metal', now(), now()),
('Djavan', 'Brasil', 'MPB', now(), now()),
('Michael Teló', 'Brasil', 'Sertanejo', now(), now()),

COMMIT;
