CREATE TABLE album_artist_role (
    id           BIGSERIAL PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    description  VARCHAR(255) NOT NULL,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE album_artist (
  album_id   BIGINT NOT NULL,
  artist_id  BIGINT NOT NULL,
  role_id    BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_album_artist
    PRIMARY KEY (album_id, artist_id),

  CONSTRAINT fk_album_artist_album
    FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE CASCADE,

  CONSTRAINT fk_album_artist_artist
    FOREIGN KEY (artist_id) REFERENCES artist(id) ON DELETE RESTRICT,

  CONSTRAINT fk_album_artist_role
    FOREIGN KEY (role_id) REFERENCES album_artist_role(id) ON DELETE RESTRICT
);

CREATE INDEX ix_album_artist_artist ON album_artist (artist_id);
CREATE INDEX ix_album_artist_role   ON album_artist (role_id);

-- ==========================================================
-- Relaciona álbuns -> artistas como PRIMARY (artista principal)

-- 0) Garante que o role PRIMARY existe (opcional, mas recomendado)
INSERT INTO album_artist_role (code, description)
VALUES ('PRIMARY', 'Artista principal do álbum')
ON CONFLICT (code) DO NOTHING;
-- 1) Resolve o role_id uma vez
WITH role_primary AS (
  SELECT id AS role_id
  FROM album_artist_role
  WHERE code = 'PRIMARY'
),
-- 2) Mapeia (artist_name, album_title, release_year)
data(artist_name, title, release_year) AS (
  VALUES
  -- =========================
  -- TITÃS
  ('Titãs', 'Titãs', 1984),
  ('Titãs', 'Televisão', 1985),
  ('Titãs', 'Cabeça Dinossauro', 1986),
  ('Titãs', 'Jesus Não Tem Dentes no País dos Banguelas', 1987),
  ('Titãs', 'Õ Blésq Blom', 1989),
  ('Titãs', 'Tudo ao Mesmo Tempo Agora', 1991),
  ('Titãs', 'Titanomaquia', 1993),
  ('Titãs', 'Domingo', 1995),
  ('Titãs', 'Volume Dois', 1998),
  ('Titãs', 'As Dez Mais', 1999),
  ('Titãs', 'A Melhor Banda de Todos os Tempos da Última Semana', 2001),
  ('Titãs', 'Como Estão Vocês?', 2003),
  ('Titãs', 'Sacos Plásticos', 2009),
  ('Titãs', 'Nheengatu', 2014),
  ('Titãs', 'Doze Flores Amarelas', 2018),
  ('Titãs', 'Titãs Trio Acústico', 2021),
  ('Titãs', 'Olho Furta-cor', 2022),
  -- SKANK
  ('Skank', 'Skank', 1992),
  ('Skank', 'Calango', 1994),
  ('Skank', 'O Samba Poconé', 1996),
  ('Skank', 'Siderado', 1998),
  ('Skank', 'Maquinarama', 2000),
  ('Skank', 'Cosmotron', 2003),
  ('Skank', 'Carrossel', 2006),
  ('Skank', 'Estandarte', 2008),
  ('Skank', 'Velocia', 2014),
  -- CAPITAL INICIAL
  ('Capital Inicial', 'Capital Inicial', 1986),
  ('Capital Inicial', 'Independência', 1987),
  ('Capital Inicial', 'Você não Precisa Entender', 1988),
  ('Capital Inicial', 'Todos os Lados', 1989),
  ('Capital Inicial', 'Eletricidade', 1991),
  ('Capital Inicial', 'Rua 47', 1995),
  ('Capital Inicial', 'Atrás dos Olhos', 1998),
  ('Capital Inicial', 'Rosas e Vinho Tinto', 2002),
  ('Capital Inicial', 'Gigante!', 2004),
  ('Capital Inicial', 'MTV Especial: Aborto Elétrico', 2005),
  ('Capital Inicial', 'Eu Nunca Disse Adeus', 2007),
  ('Capital Inicial', 'Das Kapital', 2010),
  ('Capital Inicial', 'Saturno', 2012),
  ('Capital Inicial', 'Sonora', 2018),
  -- OS PARALAMAS DO SUCESSO
  ('Os Paralamas do Sucesso', 'Cinema Mudo', 1983),
  ('Os Paralamas do Sucesso', 'O Passo do Lui', 1984),
  ('Os Paralamas do Sucesso', 'Selvagem?', 1986),
  ('Os Paralamas do Sucesso', 'Bora-Bora', 1988),
  ('Os Paralamas do Sucesso', 'Big Bang', 1989),
  ('Os Paralamas do Sucesso', 'Os Grãos', 1991),
  ('Os Paralamas do Sucesso', 'Severino', 1994),
  ('Os Paralamas do Sucesso', 'Hey Na Na', 1998),
  ('Os Paralamas do Sucesso', 'Longo Caminho', 2002),
  ('Os Paralamas do Sucesso', 'Hoje', 2005),
  ('Os Paralamas do Sucesso', 'Brasil Afora', 2009),
  ('Os Paralamas do Sucesso', 'Sinais do Sim', 2017),

  -- JOTA QUEST
  ('Jota Quest','Jota Quest', 1996),
  ('Jota Quest','De Volta ao Planeta', 1998),
  ('Jota Quest','Oxigênio', 2000),
  ('Jota Quest','Discotecagem Pop Variada', 2002),
  ('Jota Quest','Até Onde Vai', 2005),
  ('Jota Quest','La Plata', 2008),
  ('Jota Quest','Funky Funky Boom Boom', 2013),
  ('Jota Quest','Pancadélico', 2015),
-- =========================
-- CHARLIE BROWN JR.
('Charlie Brown Jr.', 'Transpiração Contínua Prolongada', 1997),
('Charlie Brown Jr.', 'Preço Curto... Prazo Longo', 1999),
('Charlie Brown Jr.', 'Nadando com os Tubarões', 2000),
('Charlie Brown Jr.', 'Bocas Ordinárias', 2002),
('Charlie Brown Jr.', 'Tamo Aí na Atividade', 2004),
('Charlie Brown Jr.', 'Ritmo, Ritual e Responsa', 2007),
('Charlie Brown Jr.', 'Camisa 10 Joga Bola Até na Chuva', 2009),
('Charlie Brown Jr.', 'La Familia 013', 2013),
  -- BARÃO VERMELHO
  ('Barão Vermelho','Barão Vermelho', 1982),
  ('Barão Vermelho','Barão Vermelho 2', 1983),
  ('Barão Vermelho','Maior Abandonado', 1984),
  ('Barão Vermelho','Declare Guerra', 1986),
  ('Barão Vermelho','Rock''n Geral', 1987),
  ('Barão Vermelho','Carnaval', 1988),
  ('Barão Vermelho','Na Calada da Noite', 1991),
  ('Barão Vermelho','Carne Crua', 1994),
  -- CASSIA ELLER
  -- =========================
  ('Cássia Eller','Cássia Eller', 1990),
  ('Cássia Eller','O Marginal', 1992),
  ('Cássia Eller','Cássia Eller (1994)', 1994),
  ('Cássia Eller','Veneno Antimonotonia', 1997),
  ('Cássia Eller','Com Você... Meu Mundo Ficaria Completo', 1999),
  -- MARISA MONTE
  -- =========================
  ('Marisa Monte','Mais', 1991),
  ('Marisa Monte','Verde, Anil, Amarelo, Cor-de-Rosa e Carvão', 1994),
  ('Marisa Monte','Barulhinho Bom', 1996),
  ('Marisa Monte','Memórias, Crônicas e Declarações de Amor', 2000),
  ('Marisa Monte','Universo ao Meu Redor', 2006),
  ('Marisa Monte','Infinito Particular', 2006),
  ('Marisa Monte','O Que Você Quer Saber de Verdade', 2011),
  ('Marisa Monte','Portas', 2021),

  -- GILBERTO GIL
  -- =========================
  ('Gilberto Gil','Louvação', 1967),
  ('Gilberto Gil','Gilberto Gil', 1968),
  ('Gilberto Gil','Refazenda', 1975),
  ('Gilberto Gil','Realce', 1979),
  ('Gilberto Gil','Raça Humana', 1984),
  ('Gilberto Gil','Quanta', 1997),
  ('Gilberto Gil','Ok Ok Ok', 2018),
  -- CAETANO VELOSO
  ('Caetano Veloso','Caetano Veloso', 1968),
  ('Caetano Veloso','Tropicália ou Panis et Circencis', 1968),
  ('Caetano Veloso','Transa', 1972),
  ('Caetano Veloso','Bicho', 1977),
  ('Caetano Veloso','Estrangeiro', 1989),
  ('Caetano Veloso','Livro', 1997),
  ('Caetano Veloso','Meu Coco', 2021),
  -- LULU SANTOS
  ('Lulu Santos','Tempos Modernos', 1982),
  ('Lulu Santos','O Ritmo do Momento', 1983),
  ('Lulu Santos','Tudo Azul', 1984),
  ('Lulu Santos','Normal', 1985),
  ('Lulu Santos','Toda Forma de Amor', 1988),
  ('Lulu Santos','Liga Lá', 1997),
  ('Lulu Santos','Baby Baby!', 2010),
  -- METALLICA
  ('Metallica','Kill ''Em All', 1983),
  ('Metallica','Ride the Lightning', 1984),
  ('Metallica','Master of Puppets', 1986),
  ('Metallica','...And Justice for All', 1988),
  ('Metallica','Metallica (Black Album)', 1991),
  ('Metallica','Load', 1996),
  ('Metallica','Reload', 1997),
  ('Metallica','St. Anger', 2003),
  ('Metallica','Death Magnetic', 2008),
  ('Metallica','Hardwired... to Self-Destruct', 2016),
  ('Metallica','72 Seasons', 2023),
  ('Metallica','Live Shit: Binge & Purge', 1993),
  ('Metallica','S&M', 1999),
  ('Metallica','Orgullo, Pasión y Gloria: Tres Noches en la Ciudad de México', 2009),
  ('Metallica','Through the Never (Live)', 2013),
  ('Metallica','S&M2', 2020),
  ('Metallica','Enter Sandman', 1991),
  ('Metallica','Nothing Else Matters', 1992),
  ('Metallica','The Unforgiven', 1991),
  ('Metallica','One', 1989),
  ('Metallica','The $5.98 E.P. – Garage Days Re-Revisited', 1987),
  ('Metallica','Beyond Magnetic', 2011),
  -- NIRVANA
  -- =========================
  ('Nirvana','Bleach', 1989),
  ('Nirvana','Nevermind', 1991),
  ('Nirvana','In Utero', 1993),
  ('Nirvana','MTV Unplugged in New York', 1994),
  ('Nirvana','From the Muddy Banks of the Wishkah', 1996),
  ('Nirvana','Live at Reading', 2009),
  ('Nirvana','Smells Like Teen Spirit', 1991),
  ('Nirvana','Come as You Are', 1992),
  ('Nirvana','Lithium', 1992),
  ('Nirvana','In Bloom', 1992),
  ('Nirvana','Heart-Shaped Box', 1993),
  ('Nirvana','Hormoaning', 1992),
  ('Nirvana','Incesticide', 1992),
  ('Nirvana','Nirvana', 2002),
  ('Nirvana','Sliver: The Best of the Box', 2005),
  -- PEARL JAM
  ('Pearl Jam','Ten', 1991),
  ('Pearl Jam','Vs.', 1993),
  ('Pearl Jam','Vitalogy', 1994),
  ('Pearl Jam','No Code', 1996),
  ('Pearl Jam','Yield', 1998),
  ('Pearl Jam','Binaural', 2000),
  ('Pearl Jam','Riot Act', 2002),
  ('Pearl Jam','Pearl Jam', 2006),
  ('Pearl Jam','Backspacer', 2009),
  ('Pearl Jam','Lightning Bolt', 2013),
  ('Pearl Jam','Gigaton', 2020),
  ('Pearl Jam','Live on Two Legs', 1998),
  ('Pearl Jam','Live at the Gorge 05/06', 2007),
  ('Pearl Jam','Let’s Play Two', 2017),
  ('Pearl Jam','Gigaton Tour Live', 2022),
  ('Pearl Jam','Alive', 1991),
  ('Pearl Jam','Jeremy', 1992),
  ('Pearl Jam','Even Flow', 1992),
  ('Pearl Jam','Black', 1991),
  ('Pearl Jam','Better Man', 1995),
  ('Pearl Jam','Lost Dogs', 2003),
  ('Pearl Jam','rearviewmirror (greatest hits 1991–2003)', 2004),
  -- RED HOT CHILI PEPPERS
  ('Red Hot Chili Peppers','The Red Hot Chili Peppers', 1984),
  ('Red Hot Chili Peppers','Freaky Styley', 1985),
  ('Red Hot Chili Peppers','The Uplift Mofo Party Plan', 1987),
  ('Red Hot Chili Peppers','Mother''s Milk', 1989),
  ('Red Hot Chili Peppers','Blood Sugar Sex Magik', 1991),
  ('Red Hot Chili Peppers','Californication', 1999),
  ('Red Hot Chili Peppers','By the Way', 2002),
  ('Red Hot Chili Peppers','Stadium Arcadium', 2006),
  ('Red Hot Chili Peppers','I''m with You', 2011),
  ('Red Hot Chili Peppers','The Getaway', 2016),
  ('Red Hot Chili Peppers','Unlimited Love', 2022),
  ('Red Hot Chili Peppers','Live in Hyde Park', 2004),
  ('Red Hot Chili Peppers','Under the Bridge', 1992),
  ('Red Hot Chili Peppers','Give It Away', 1991),
  ('Red Hot Chili Peppers','Californication', 2000),
  ('Red Hot Chili Peppers','Scar Tissue', 1999),
  ('Red Hot Chili Peppers','Can''t Stop', 2002),
  ('Red Hot Chili Peppers','Rock & Roll Hall of Fame Covers EP', 2012),
  ('Red Hot Chili Peppers','What Hits!?', 1992),
  ('Red Hot Chili Peppers','Greatest Hits', 2003),
  -- LINKIN PARK
  -- =========================
  ('Linkin Park','Hybrid Theory', 2000),
  ('Linkin Park','Meteora', 2003),
  ('Linkin Park','Minutes to Midnight', 2007),
  ('Linkin Park','A Thousand Suns', 2010),
  ('Linkin Park','Living Things', 2012),
  ('Linkin Park','The Hunting Party', 2014),
  ('Linkin Park','One More Light', 2017),
  ('Linkin Park','Live in Texas', 2003),
  ('Linkin Park','Road to Revolution: Live at Milton Keynes', 2008),
  ('Linkin Park','One More Light Live', 2017),
  ('Linkin Park','In the End', 2001),
  ('Linkin Park','Numb', 2003),
  ('Linkin Park','Crawling', 2001),
  ('Linkin Park','Somewhere I Belong', 2003),
  ('Linkin Park','What I''ve Done', 2007),
  ('Linkin Park','Collision Course (with Jay-Z)', 2004),
  ('Linkin Park','Papercuts – Singles Collection 2000–2023', 2024),
  -- COLDPLAY
  ('Coldplay','Parachutes', 2000),
  ('Coldplay','A Rush of Blood to the Head', 2002),
  ('Coldplay','X&Y', 2005),
  ('Coldplay','Viva la Vida or Death and All His Friends', 2008),
  ('Coldplay','Mylo Xyloto', 2011),
  ('Coldplay','Ghost Stories', 2014),
  ('Coldplay','A Head Full of Dreams', 2015),
  ('Coldplay','Everyday Life', 2019),
  ('Coldplay','Music of the Spheres', 2021),
  ('Coldplay','Live 2003', 2003),
  ('Coldplay','LeftRightLeftRightLeft', 2009),
  ('Coldplay','Ghost Stories Live 2014', 2014),
  ('Coldplay','Yellow', 2000),
  ('Coldplay','The Scientist', 2002),
  ('Coldplay','Clocks', 2002),
  ('Coldplay','Viva la Vida', 2008),
  ('Coldplay','Fix You', 2005),
  ('Coldplay','Safety EP', 1998),
  ('Coldplay','The Blue Room', 1999),
  ('Coldplay','Prospekt’s March', 2008),
  ('Coldplay','Coldplay: Reimagined', 2017),
  -- U2
  -- =========================
  ('U2','Boy', 1980),
  ('U2','October', 1981),
  ('U2','War', 1983),
  ('U2','The Unforgettable Fire', 1984),
  ('U2','The Joshua Tree', 1987),
  ('U2','Achtung Baby', 1991),
  ('U2','Zooropa', 1993),
  ('U2','Pop', 1997),
  ('U2','All That You Can''t Leave Behind', 2000),
  ('U2','How to Dismantle an Atomic Bomb', 2004),
  ('U2','Songs of Innocence', 2014),
  ('U2','Songs of Experience', 2017),
  ('U2','Under a Blood Red Sky', 1983),
  ('U2','Rattle and Hum', 1988),
  ('U2','Zoo TV Live', 1993),
  ('U2','Live from Paris', 2007),
  ('U2','With or Without You', 1987),
  ('U2','One', 1992),
  ('U2','Beautiful Day', 2000),
  ('U2','Sunday Bloody Sunday', 1983),
  ('U2','I Still Haven''t Found What I''m Looking For', 1987),
  ('U2','Wide Awake in America', 1985),
  ('U2','The Best of 1980–1990', 1998),
  ('U2','The Best of 1990–2000', 2002),
  ('U2','U218 Singles', 2006),
  -- QUEEN
  ('Queen','Queen', 1973),
  ('Queen','Queen II', 1974),
  ('Queen','Sheer Heart Attack', 1974),
  ('Queen','A Night at the Opera', 1975),
  ('Queen','A Day at the Races', 1976),
  ('Queen','News of the World', 1977),
  ('Queen','Jazz', 1978),
  ('Queen','The Game', 1980),
  ('Queen','Hot Space', 1982),
  ('Queen','The Works', 1984),
  ('Queen','A Kind of Magic', 1986),
  ('Queen','The Miracle', 1989),
  ('Queen','Innuendo', 1991),
  ('Queen','Made in Heaven', 1995),
  ('Queen','Live Killers', 1979),
  ('Queen','Live Magic', 1986),
  ('Queen','Live at Wembley ''86', 1992),
  ('Queen','Queen Rock Montreal', 2007),
  ('Queen','Bohemian Rhapsody', 1975),
  ('Queen','We Will Rock You', 1977),
  ('Queen','We Are the Champions', 1977),
  ('Queen','Another One Bites the Dust', 1980),
  ('Queen','Don''t Stop Me Now', 1979),
  ('Queen','Greatest Hits', 1981),
  ('Queen','Greatest Hits II', 1991),
  ('Queen','Greatest Hits III', 1999),
  ('Queen','Absolute Greatest', 2009),
  -- THE BEATLES
  ('The Beatles','Please Please Me', 1963),
  ('The Beatles','With the Beatles', 1963),
  ('The Beatles','A Hard Day''s Night', 1964),
  ('The Beatles','Beatles for Sale', 1964),
  ('The Beatles','Help!', 1965),
  ('The Beatles','Rubber Soul', 1965),
  ('The Beatles','Revolver', 1966),
  ('The Beatles','Sgt. Pepper''s Lonely Hearts Club Band', 1967),
  ('The Beatles','The Beatles (White Album)', 1968),
  ('The Beatles','Abbey Road', 1969),
  ('The Beatles','Let It Be', 1970),
  ('The Beatles','Live at the Hollywood Bowl', 1977),
  ('The Beatles','Hey Jude', 1968),
  ('The Beatles','Come Together', 1969),
  ('The Beatles','I Want to Hold Your Hand', 1963),
  ('The Beatles','Magical Mystery Tour (EP original UK)', 1967),
  ('The Beatles','1962–1966', 1973),
  ('The Beatles','1967–1970', 1973),
  ('The Beatles','Anthology 1', 1995),
  ('The Beatles','Anthology 2', 1996),
  ('The Beatles','Anthology 3', 1996),
  ('The Beatles','1', 2000),
  -- PINK FLOYD
  ('Pink Floyd','The Piper at the Gates of Dawn', 1967),
  ('Pink Floyd','A Saucerful of Secrets', 1968),
  ('Pink Floyd','More', 1969),
  ('Pink Floyd','Ummagumma', 1969),
  ('Pink Floyd','Atom Heart Mother', 1970),
  ('Pink Floyd','Meddle', 1971),
  ('Pink Floyd','The Dark Side of the Moon', 1973),
  ('Pink Floyd','Wish You Were Here', 1975),
  ('Pink Floyd','Animals', 1977),
  ('Pink Floyd','The Wall', 1979),
  ('Pink Floyd','The Final Cut', 1983),
  ('Pink Floyd','A Momentary Lapse of Reason', 1987),
  ('Pink Floyd','The Division Bell', 1994),
  ('Pink Floyd','Delicate Sound of Thunder', 1988),
  ('Pink Floyd','Pulse', 1995),
  ('Pink Floyd','Another Brick in the Wall (Part 2)', 1979),
  ('Pink Floyd','Money', 1973),
  ('Pink Floyd','Time', 1973),
  ('Pink Floyd','Comfortably Numb', 1979),
  ('Pink Floyd','Relics', 1971),
  ('Pink Floyd','A Collection of Great Dance Songs', 1981),
  ('Pink Floyd','Works', 1983),
  ('Pink Floyd','Echoes: The Best of Pink Floyd', 2001),
  -- AC/DC
  -- =========================
  ('AC/DC','High Voltage', 1975),
  ('AC/DC','T.N.T.', 1975),
  ('AC/DC','Dirty Deeds Done Dirt Cheap', 1976),
  ('AC/DC','Let There Be Rock', 1977),
  ('AC/DC','Powerage', 1978),
  ('AC/DC','Highway to Hell', 1979),
  ('AC/DC','Back in Black', 1980),
  ('AC/DC','For Those About to Rock We Salute You', 1981),
  ('AC/DC','The Razors Edge', 1990),
  ('AC/DC','Ballbreaker', 1995),
  ('AC/DC','Stiff Upper Lip', 2000),
  ('AC/DC','Black Ice', 2008),
  ('AC/DC','Rock or Bust', 2014),
  ('AC/DC','Power Up', 2020),
  ('AC/DC','If You Want Blood You''ve Got It', 1978),
  ('AC/DC','AC/DC Live', 1992),
  ('AC/DC','Live at River Plate', 2012),
  ('AC/DC','Thunderstruck', 1990),
  ('AC/DC','You Shook Me All Night Long', 1980),
  ('AC/DC','Who Made Who', 1986),
  ('AC/DC','Bonfire', 1997),
  ('AC/DC','Backtracks', 2009),
  -- IMAGINE DRAGONS
  ('Imagine Dragons','Night Visions', 2012),
  ('Imagine Dragons','Smoke + Mirrors', 2015),
  ('Imagine Dragons','Evolve', 2017),
  ('Imagine Dragons','Origins', 2018),
  ('Imagine Dragons','Mercury – Act 1', 2021),
  ('Imagine Dragons','Mercury – Act 2', 2022),
  ('Imagine Dragons','Loom', 2024),
  ('Imagine Dragons','Live at AllSaints Studios', 2013),
  ('Imagine Dragons','Radioactive', 2012),
  ('Imagine Dragons','Demons', 2013),
  ('Imagine Dragons','Believer', 2017),
  ('Imagine Dragons','Thunder', 2017),
  ('Imagine Dragons','Whatever It Takes', 2017),
  ('Imagine Dragons','Imagine Dragons EP', 2009),
  ('Imagine Dragons','Hell and Silence', 2010),
  ('Imagine Dragons','It’s Time', 2011),
  -- ARCTIC MONKEYS
  ('Arctic Monkeys','Whatever People Say I Am, That''s What I''m Not', 2006),
  ('Arctic Monkeys','Favourite Worst Nightmare', 2007),
  ('Arctic Monkeys','Humbug', 2009),
  ('Arctic Monkeys','Suck It and See', 2011),
  ('Arctic Monkeys','AM', 2013),
  ('Arctic Monkeys','Tranquility Base Hotel & Casino', 2018),
  ('Arctic Monkeys','The Car', 2022),
  ('Arctic Monkeys','Live at the Royal Albert Hall', 2020),
  ('Arctic Monkeys','I Bet You Look Good on the Dancefloor', 2005),
  ('Arctic Monkeys','When the Sun Goes Down', 2006),
  ('Arctic Monkeys','Do I Wanna Know?', 2013),
  ('Arctic Monkeys','R U Mine?', 2012),
  ('Arctic Monkeys','505', 2007),
  ('Arctic Monkeys','Five Minutes with Arctic Monkeys', 2005),
  ('Arctic Monkeys','Who the F*** Are Arctic Monkeys?', 2006),
  -- BON JOVI
  ('Bon Jovi','Bon Jovi', 1984),
  ('Bon Jovi','7800° Fahrenheit', 1985),
  ('Bon Jovi','Slippery When Wet', 1986),
  ('Bon Jovi','New Jersey', 1988),
  ('Bon Jovi','Keep the Faith', 1992),
  ('Bon Jovi','These Days', 1995),
  ('Bon Jovi','Crush', 2000),
  ('Bon Jovi','Bounce', 2002),
  ('Bon Jovi','Have a Nice Day', 2005),
  ('Bon Jovi','Lost Highway', 2007),
  ('Bon Jovi','The Circle', 2009),
  ('Bon Jovi','What About Now', 2013),
  ('Bon Jovi','This House Is Not for Sale', 2016),
  ('Bon Jovi','2020', 2020),
  ('Bon Jovi','Forever', 2024),
  -- EVANESCENCE
  ('Evanescence','Fallen', 2003),
  ('Evanescence','The Open Door', 2006),
  ('Evanescence','Evanescence', 2011),
  ('Evanescence','The Bitter Truth', 2021),
  -- MICHAEL TELÓ
  ('Michael Teló','Balada Sertaneja', 2009),
  ('Michael Teló','Michel Teló – Ao Vivo', 2012),
  ('Michael Teló','Bem Sertanejo – O Musical (Ao Vivo)', 2017),
  -- GUNS N' ROSES
  ('Guns N’ Roses','Appetite for Destruction', 1987),
  ('Guns N’ Roses','G N'' R Lies', 1988),
  ('Guns N’ Roses','Use Your Illusion I', 1991),
  ('Guns N’ Roses','Use Your Illusion II', 1991),
  ('Guns N’ Roses','The Spaghetti Incident?', 1993),
  ('Guns N’ Roses','Chinese Democracy', 2008),
  ('Guns N’ Roses','Live Era ''87–''93', 1999),
  -- MIKE SHINODA
  ('Mike Shinoda','Post Traumatic', 2018),
  ('Mike Shinoda','Dropped Frames, Vol. 1', 2020),
  ('Mike Shinoda','Dropped Frames, Vol. 2', 2020),
  ('Mike Shinoda','Dropped Frames, Vol. 3', 2020),
  ('Mike Shinoda','Live in London', 2019),
  -- STEREOPHONICS
  ('Stereophonics','Word Gets Around', 1997),
  ('Stereophonics','Performance and Cocktails', 1999),
  ('Stereophonics','Just Enough Education to Perform', 2001),
  ('Stereophonics','You Gotta Go There to Come Back', 2003),
  ('Stereophonics','Language. Sex. Violence. Other?', 2005),
  ('Stereophonics','Pull the Pin', 2007),
  ('Stereophonics','Keep Calm and Carry On', 2009),
  ('Stereophonics','Graffiti on the Train', 2013),
  ('Stereophonics','Keep the Village Alive', 2015),
  ('Stereophonics','Scream Above the Sounds', 2017),
  ('Stereophonics','Kind', 2019),
  ('Stereophonics','Oochya!', 2022),
  ('Stereophonics','Make ''Em Laugh, Make ''Em Cry, Make ''Em Wait', 2025),
  ('Stereophonics','Live from Dakota', 2006),
  ('Stereophonics','Decade in the Sun: Live at Cardiff Castle', 2008),
  -- SERJ TANKIAN
  ('Serj Tankian','Elect the Dead', 2007),
  ('Serj Tankian','Imperfect Harmonies', 2010),
  ('Serj Tankian','Harakiri', 2012),
  ('Serj Tankian','Orca', 2013),
  ('Serj Tankian','Covers, Collaborations & Collages', 2025),
  ('Serj Tankian','Elect the Dead Symphony (Live with Orchestra)', 2010),
  -- DJAVAN
  ('Djavan','A Voz, o Violão, a Música de Djavan', 1976),
  ('Djavan','Djavan', 1979),
  ('Djavan','Alumbramento', 1980),
  ('Djavan','Seduzir', 1981),
  ('Djavan','Luz', 1982),
  ('Djavan','Lilás', 1984),
  ('Djavan','Meu Lado', 1986),
  ('Djavan','Não É Azul, mas É Mar', 1987),
  ('Djavan','Djavan (1989)', 1989),
  ('Djavan','Coisa de Acender', 1992),
  ('Djavan','Novena', 1994),
  ('Djavan','Malásia', 1996),
  ('Djavan','Bicho Solto', 1998),
  ('Djavan','Milagreiro', 2001),
  ('Djavan','Vaidade', 2004),
  ('Djavan','Matizes', 2007),
  ('Djavan','Ária', 2010),
  ('Djavan','Rua dos Amores', 2012),
  ('Djavan','Vidas pra Contar', 2015),
  ('Djavan','Vesúvio', 2018),
  ('Djavan','D', 2022),
  ('Djavan','Origem', 2024),
  ('Djavan','Djavan Ao Vivo', 1999),
  ('Djavan','Multishow Ao Vivo – Djavan', 2011),
  ('Djavan','Voz & Violão – Ao Vivo', 2015)
)
-- 3) Faz os joins e insere
INSERT INTO album_artist (album_id, artist_id, role_id)
SELECT
  a.id AS album_id,
  r.id AS artist_id,
  rp.role_id
FROM data d
JOIN artist r
  ON r.name = d.artist_name
JOIN album a
  ON a.title = d.title
 AND a.release_year = d.release_year
CROSS JOIN role_primary rp
ON CONFLICT (album_id, artist_id)
DO UPDATE SET role_id = EXCLUDED.role_id;
